# model
asr: facebook/wav2vec2-base-960h
# asr: speechbrain/asr-crdnn-rnnlm-librispeech
# asr: pretrained_models/stt_en_conformer_transducer_small.nemo

# dataset
# dataset_name: librispeech
# dataset_dir: /home/server17/hdd/changhun_workspace/LibriSpeech
dataset_name: chime
dataset_dir: /home/server17/hdd/changhun_workspace/CHiME3
# dataset_name: commonvoice
# dataset_dir: /home/server17/hdd/changhun_workspace/cv-corpus-5.1-2020-06-22/en
# dataset_name: ted
# dataset_dir: /home/server17/hdd/changhun_workspace/TEDLIUM_release2/test
split: [test-other]
extra_noise: 0.00
sample_rate: 16000
batch_size: 1

# optimizer & train hyparameters
optimizer: AdamW
lr: 2e-6
scheduler: null
steps: 10
train_params: [all] # currently supported: all, feature, LN, linear(linear probing), da
bias_only: false
episodic: true # load pretrained model for every batch

# methods and general hyperparameters
method: [original] # currently supported: original, em_uncertainty, em_sparse, em_joint, em_aug, (cr), cr_feature, da, contrastive_temporal, p_logp

teacher_student: false
momentum: 0.99

stochastic_restoration: false
restore_prob: 0.01

prob_threshold: 0.9
entropy_threshold: 0.05

# method-specific hyperparameters
num_augs: 1
aug_method: augmix # augmix, standard
not_blank: true
reweight: true
em_coef: 1
temp: 2.5 # temperature smoothing
div_coef: 0

# memory queue
use_memory_queue: false
queue_size: 256
n_neighbors: 6

# device
device: cuda

# logging
log_dir: exps/test