### model
# asr: facebook/wav2vec2-base-960h
# asr: speechbrain/asr-crdnn-rnnlm-librispeech
# asr: speechbrain/asr-crdnn-transformerlm-librispeech
# asr: speechbrain/asr-transformer-transformerlm-librispeech
asr: speechbrain/asr-conformersmall-transformerlm-librispeech
# asr: pretrained_models/stt_en_conformer_transducer_small.nemo
# asr: pretrained_models/stt_en_conformer_transducer_large.nemo

### dataset
# dataset_name: librispeech
# dataset_dir: /home/server17/hdd/changhun_workspace/LibriSpeech
dataset_name: chime
dataset_dir: /home/server17/hdd/changhun_workspace/CHiME3
# dataset_name: ted
# dataset_dir: /home/server17/hdd/changhun_workspace/TEDLIUM_release2/test
# dataset_name: valentini
# dataset_dir: /home/server17/hdd/changhun_workspace/Valentini
# dataset_name: commonvoice
# dataset_dir: /home/server17/hdd/changhun_workspace/cv-corpus-5.1-2020-06-22/en
split: [test-other]
extra_noise: 0.00
noise_type: null  # currently supported: null, AirConditioner_6, AirportAnnouncements_2, Babble_4, CopyMachine_2, Munching_3, Neighbor_6, ShuttingDoor_6, Typing_2, VacuumCleaner_1
sample_rate: 16000
batch_size: 1

### device
device: cuda

### logging
log_dir: exps/test

### optimizer & train hyparameters
optimizer: AdamW
lr: 2e-5
train_params: [all] # currently supported: all, feature, LN, linear(linear probing)
steps: 10
bias_only: false
episodic: true # load pretrained model again for every batch

### learning rate scheduler
scheduler: null # null or CosineAnnealingLR
t_max: 10
eta_min: 1e-5
##################################################################
### methods & other hyperparameters
## currently supported methods:
## original, em_uncertainty, em_sparse, em_dropout, greedy_pseudo_labeling, gce, ctc, beam_search_max, beam_search_all, beam_search_negative_sampling, diversity_maximization
method: [beam_search_max, beam_search_negative_sampling]
decoding_method: beam_search # greedy_search or beam_search

temp: 2.5 # temperature smoothing
em_coef: 0.3
not_blank: true
certain_only: true
reweight: true

### uncertainty aware pseudo-labeling
prob_threshold: 0.9
entropy_threshold: 0.05

### beam search and negative sampling
beam_width: 10
num_positives: 1 # for beam_search_all
num_negatives: 5
negative_sampling_method: beam_candidate # random, beam_candidate
ns_coef: 1

### diversity maximization
dm_coef: 0.1

### label smoothing
label_smoothing: 0
##################################################################

### selective adaptation
selective_adaptation: false
ood_threshold: -0.45

### seed for reproductivity
seed: 42