# model
# asr: facebook/wav2vec2-base-960h
# asr: speechbrain/asr-crdnn-rnnlm-librispeech
asr: pretrained_models/stt_en_conformer_transducer_small.nemo

# dataset
# dataset_name: librispeech
# dataset_dir: /mnt/hdd0/changhun_workspace/LibriSpeech
# dataset_name: chime
# dataset_dir: /home/server08/hdd0/changhun_workspace/CHiME3
# dataset_name: commonvoice
# dataset_dir: /home/server08/hdd0/changhun_workspace/cv-corpus-5.1-2020-06-22/en
dataset_name: ted
dataset_dir: /home/server08/hdd0/changhun_workspace/TEDLIUM_release2/test
split: [test-other]
batch_size: 1
extra_noise: 0
sample_rate: 16000

# optimizer & train hyparameters
optimizer: AdamW
lr: 2e-5
scheduler: null
steps: 1
train_params: [LN] # currently supported: all, feature, LN, linear(linear probing)
bias_only: false
episodic: true # load pretrained model for every batch

# methods and general hyperparameters
method: cr # currently supported: original, em_uncertainty, em_sparse, cr
teacher_student: false
momentum: 0.99

stochastic_restoration: false
restore_prob: 0.01

prob_threshold: 0.9
entropy_threshold: 0.05

# method-specific hyperparameters
not_blank: true
reweight: true
em_coef: 0.3
temp: 2.5 # temperature smoothing
div_coef: 0
aug_type: augmix

# memory queue
use_memory_queue: false
queue_size: 256
n_neighbors: 6

# device
device: cuda

# logging
log_dir: exps/cr_linear_attention