CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=chime \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/CHiME3 \
    batch_size=1 \
    lr=1e-6 \
    steps=10 \
    'train_params=[all]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/suta_attn \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=ted \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/TEDLIUM_release2/test \
    batch_size=1 \
    lr=1e-6 \
    steps=10 \
    'train_params=[all]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/suta_attn \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=valentini \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/Valentini \
    batch_size=1 \
    lr=1e-6 \
    steps=10 \
    'train_params=[all]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/suta_attn \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=AirConditioner_6 \
    batch_size=1 \
    lr=1e-6 \
    steps=10 \
    'train_params=[all]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/suta_attn \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=AirportAnnouncements_2 \
    batch_size=1 \
    lr=1e-6 \
    steps=10 \
    'train_params=[all]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/suta_attn \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Babble_4 \
    batch_size=1 \
    lr=1e-6 \
    steps=10 \
    'train_params=[all]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/suta_attn \