CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=facebook/wav2vec2-base-960h \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=ShuttingDoor_6 \
    batch_size=1 \
    lr=2e-5 \
    steps=10 \
    'train_params=[feature]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/ctc_aleatoric \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=facebook/wav2vec2-base-960h \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Typing_2 \
    batch_size=1 \
    lr=2e-5 \
    steps=10 \
    'train_params=[feature]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/ctc_aleatoric \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=facebook/wav2vec2-base-960h \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=VacuumCleaner_1 \
    batch_size=1 \
    lr=2e-5 \
    steps=10 \
    'train_params=[feature]' \
    'method=[original]' \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/ctc_aleatoric \