CUDA_VISIBLE_DEVICES=0 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=chime \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/CHiME3 \
    batch_size=4 \
    lr=2e-5 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    prob_threshold=1 \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=0 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=ted \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/TEDLIUM_release2/test \
    batch_size=4 \
    lr=2e-5 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    prob_threshold=1 \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=0 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=valentini \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/Valentini \
    batch_size=4 \
    lr=2e-5 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    prob_threshold=1 \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \
