CUDA_VISIBLE_DEVICES=2 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=chime \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/CHiME3 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=2 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=ted \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/TEDLIUM_release2/test \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=2 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=valentini \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/Valentini \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=2 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=AirportAnnouncements_2 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=2 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Babble_4 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=2 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=CopyMachine_2 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

