CUDA_VISIBLE_DEVICES=1 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=librispeech \
    dataset_dir=/home/server27/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=AirportAnnouncements_2 \
    batch_size=4 \
    lr=2e-6 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_attn \

CUDA_VISIBLE_DEVICES=1 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=librispeech \
    dataset_dir=/home/server27/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Babble_4 \
    batch_size=4 \
    lr=2e-6 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_attn \

CUDA_VISIBLE_DEVICES=1 python main.py \
    asr=speechbrain/asr-crdnn-rnnlm-librispeech \
    dataset_name=librispeech \
    dataset_dir=/home/server27/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=CopyMachine_2 \
    batch_size=4 \
    lr=2e-6 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_attn \

