CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Neighbor_6 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=ShuttingDoor_6 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Typing_2 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=AirConditioner_6 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Munching_3 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=3 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=VacuumCleaner_1 \
    batch_size=1 \
    lr=1e-5 \
    steps=10 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=true \
    selective_adaptation=false \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

