CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=AirportAnnouncements_2 \
    batch_size=4 \
    lr=2e-5 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    prob_threshold=1 \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=Babble_4 \
    batch_size=4 \
    lr=2e-5 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    prob_threshold=1 \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \

CUDA_VISIBLE_DEVICES=4 python main.py \
    asr=pretrained_models/stt_en_conformer_transducer_small.nemo \
    dataset_name=librispeech \
    dataset_dir=/home/server34/hdd/changhun_workspace/nfs-client/LibriSpeech \
    noise_type=CopyMachine_2 \
    batch_size=4 \
    lr=2e-5 \
    steps=5 \
    'train_params=[all]' \
    'method=[em_joint, original]' \
    em_coef=0 \
    use_memory_queue=false \
    selective_adaptation=false \
    prob_threshold=1 \
    teacher_student=false \
    stochastic_restoration=false \
    log_dir=exps/tasper_trans \
