CUDA_VISIBLE_DEVICES=1 python main.py \
                asr=facebook/wav2vec2-base-960h \
                steps=10 \
                dataset_name=ted \
                dataset_dir=/home/server08/hdd0/changhun_workspace/TEDLIUM_release2/test \
                temp=2.5 \
                episodic=True\
                not_blank=True \
                em_coef=0.3 \
                reweight=Ture \
                log_dir=exps \
                lr=2e-5 \
                'train_params=[feature]' \
                extra_noise=0 \